listen: true
port: 8000
whitelistMode: true
whitelist:
  - 127.0.0.1
  - 192.168.1.64
basicAuthMode: false
basicAuthUser:
  username: user
  password: password
enableCorsProxy: false
securityOverride: false
autorun: true
disableThumbnails: false
thumbnailsQuality: 95
avatarThumbnailsPng: false
allowKeysExposure: false
skipContentCheck: false
disableChatBackup: true
requestOverrides: []
enableExtensions: true
extras:
  disableAutoDownload: false
  classificationModel: Cohee/distilbert-base-uncased-go-emotions-onnx
  captioningModel: Xenova/vit-gpt2-image-captioning
  embeddingModel: Cohee/jina-embeddings-v2-base-en
  promptExpansionModel: Cohee/fooocus_expansion-onnx
  speechToTextModel: Xenova/whisper-small
  textToSpeechModel: Xenova/speecht5_tts
openai:
  randomizeUserId: false
  captionSystemPrompt: ""
deepl:
  formality: default
enableServerPlugins: false
dataRoot: ./data
enableForwardedWhitelist: true
enableUserAccounts: false
enableDiscreetLogin: false
cookieSecret: ybBYQhrYnwJGwgV9uzHfq5bxw9BBe4IMAOcBfCyUlNU5fk5vtgtPuHQuDPkE0CTK0hAEqeYoKuwbgPoRzAohJg==
disableCsrfProtection: false
whitelistImportDomains:
  - localhost
  - cdn.discordapp.com
  - files.catbox.moe
  - raw.githubusercontent.com
numberOfBackups: 50
mistral:
  enablePrefix: false
sessionTimeout: 86400
protocol:
  ipv4: true
  ipv6: false
dnsPreferIPv6: false
autorunHostname: auto
autorunPortOverride: -1
requestProxy:
  enabled: false
  url: socks5://username:password@example.com:1080
  bypass:
    - localhost
    - 127.0.0.1
autheliaAuth: false
perUserBasicAuth: false
avoidLocalhost: false
chatBackupThrottleInterval: 10000
enableExtensionsAutoUpdate: true
enableDownloadableTokenizers: true
promptPlaceholder: "[Start a new chat]"
ollama:
  keepAlive: -1
claude:
  enableSystemPromptCache: false
