listen: true
port: 8000
whitelistMode: true
whitelist:
  - 127.0.0.1
  - 192.168.1.64
basicAuthMode: false
basicAuthUser:
  username: user
  password: password
enableCorsProxy: false
securityOverride: false
allowKeysExposure: false
skipContentCheck: false
requestOverrides: []
extras:
  promptExpansionModel: Cohee/fooocus_expansion-onnx
openai:
  randomizeUserId: false
  captionSystemPrompt: ""
deepl:
  formality: default
enableServerPlugins: true
dataRoot: ./data
enableForwardedWhitelist: true
enableUserAccounts: false
enableDiscreetLogin: false
disableCsrfProtection: false
whitelistImportDomains:
  - localhost
  - cdn.discordapp.com
  - files.catbox.moe
  - raw.githubusercontent.com
  - char-archive.evulid.cc
mistral:
  enablePrefix: false
sessionTimeout: 86400
protocol:
  ipv4: true
  ipv6: false
dnsPreferIPv6: false
requestProxy:
  enabled: false
  url: socks5://username:password@example.com:1080
  bypass:
    - localhost
    - 127.0.0.1
autheliaAuth: false
perUserBasicAuth: false
enableDownloadableTokenizers: true
promptPlaceholder: "[Start a new chat]"
ollama:
  keepAlive: -1
  batchSize: -1
claude:
  enableSystemPromptCache: false
  cachingAtDepth: -1
  extendedTTL: false
thumbnails:
  enabled: true
  quality: 95
  format: jpg
  dimensions:
    bg:
      - 160
      - 90
    avatar:
      - 96
      - 144
backups:
  chat:
    enabled: false
    throttleInterval: 10000
    maxTotalBackups: -1
    checkIntegrity: true
  common:
    numberOfBackups: 50
extensions:
  enabled: true
  autoUpdate: true
  models:
    autoDownload: true
    classification: Cohee/distilbert-base-uncased-go-emotions-onnx
    captioning: Xenova/vit-gpt2-image-captioning
    embedding: Cohee/jina-embeddings-v2-base-en
    speechToText: Xenova/whisper-small
    textToSpeech: Xenova/speecht5_tts
listenAddress:
  ipv4: 0.0.0.0
  ipv6: "[::]"
enableServerPluginsAutoUpdate: false
logging:
  minLogLevel: 0
  enableAccessLog: true
performance:
  memoryCacheCapacity: 100mb
  lazyLoadCharacters: false
  useDiskCache: true
ssl:
  enabled: false
  certPath: ./certs/cert.pem
  keyPath: ./certs/privkey.pem
whitelistDockerHosts: true
rateLimiting:
  preferRealIpHeader: false
browserLaunch:
  enabled: true
  hostname: auto
  port: -1
  avoidLocalhost: false
  browser: default
gemini:
  apiVersion: v1beta
