listen: true
port: 8000
whitelistMode: true
whitelist:
  - 127.0.0.1
  - 192.168.1.64
basicAuthMode: false
basicAuthUser:
  username: user
  password: password
enableCorsProxy: false
securityOverride: false
autorun: true
disableThumbnails: false
thumbnailsQuality: 95
avatarThumbnailsPng: false
allowKeysExposure: false
skipContentCheck: false
disableChatBackup: true
requestOverrides: []
enableExtensions: true
extras:
  disableAutoDownload: false
  classificationModel: Cohee/distilbert-base-uncased-go-emotions-onnx
  captioningModel: Xenova/vit-gpt2-image-captioning
  embeddingModel: Cohee/jina-embeddings-v2-base-en
  promptExpansionModel: Cohee/fooocus_expansion-onnx
  speechToTextModel: Xenova/whisper-small
  textToSpeechModel: Xenova/speecht5_tts
openai:
  randomizeUserId: false
  captionSystemPrompt: ""
deepl:
  formality: default
enableServerPlugins: false
dataRoot: ./data
enableForwardedWhitelist: true
enableUserAccounts: false
enableDiscreetLogin: false
cookieSecret: ybBYQhrYnwJGwgV9uzHfq5bxw9BBe4IMAOcBfCyUlNU5fk5vtgtPuHQuDPkE0CTK0hAEqeYoKuwbgPoRzAohJg==
disableCsrfProtection: false
whitelistImportDomains:
  - localhost
  - cdn.discordapp.com
  - files.catbox.moe
  - raw.githubusercontent.com
