listen: true
port: 8000
whitelistMode: true
whitelist:
  - 127.0.0.1
  - 192.168.1.64
basicAuthMode: false
basicAuthUser:
  username: user
  password: password
enableCorsProxy: false
securityOverride: false
autorun: true
allowKeysExposure: false
skipContentCheck: false
requestOverrides: []
extras:
  promptExpansionModel: Cohee/fooocus_expansion-onnx
openai:
  randomizeUserId: false
  captionSystemPrompt: ""
deepl:
  formality: default
enableServerPlugins: false
dataRoot: ./data
enableForwardedWhitelist: true
enableUserAccounts: false
enableDiscreetLogin: false
cookieSecret: ybBYQhrYnwJGwgV9uzHfq5bxw9BBe4IMAOcBfCyUlNU5fk5vtgtPuHQuDPkE0CTK0hAEqeYoKuwbgPoRzAohJg==
disableCsrfProtection: false
whitelistImportDomains:
  - localhost
  - cdn.discordapp.com
  - files.catbox.moe
  - raw.githubusercontent.com
mistral:
  enablePrefix: false
sessionTimeout: 86400
protocol:
  ipv4: true
  ipv6: false
dnsPreferIPv6: false
autorunHostname: auto
autorunPortOverride: -1
requestProxy:
  enabled: false
  url: socks5://username:password@example.com:1080
  bypass:
    - localhost
    - 127.0.0.1
autheliaAuth: false
perUserBasicAuth: false
avoidLocalhost: false
enableDownloadableTokenizers: true
promptPlaceholder: "[Start a new chat]"
ollama:
  keepAlive: -1
  batchSize: -1
claude:
  enableSystemPromptCache: false
  cachingAtDepth: -1
thumbnails:
  enabled: true
  quality: 95
  format: jpg
  dimensions:
    bg:
      - 160
      - 90
    avatar:
      - 96
      - 144
backups:
  chat:
    enabled: false
    throttleInterval: 10000
    maxTotalBackups: -1
  common:
    numberOfBackups: 50
extensions:
  enabled: true
  autoUpdate: true
  models:
    autoDownload: true
    classification: Cohee/distilbert-base-uncased-go-emotions-onnx
    captioning: Xenova/vit-gpt2-image-captioning
    embedding: Cohee/jina-embeddings-v2-base-en
    speechToText: Xenova/whisper-small
    textToSpeech: Xenova/speecht5_tts
cardsCacheCapacity: 100
listenAddress:
  ipv4: 0.0.0.0
  ipv6: "[::]"
minLogLevel: 0
enableServerPluginsAutoUpdate: true
